AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - 'test/**/*'

Style/OneClassPerFile:
  Exclude:
    - 'test/**/*'
