# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: fila/v1/admin.proto for package 'fila.v1'

require 'grpc'
require 'fila/v1/admin_pb'

module Fila
  module V1
    module FilaAdmin
      # Admin RPCs for operators and the CLI.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'fila.v1.FilaAdmin'

        rpc :CreateQueue, ::Fila::V1::CreateQueueRequest, ::Fila::V1::CreateQueueResponse
        rpc :DeleteQueue, ::Fila::V1::DeleteQueueRequest, ::Fila::V1::DeleteQueueResponse
        rpc :SetConfig, ::Fila::V1::SetConfigRequest, ::Fila::V1::SetConfigResponse
        rpc :GetConfig, ::Fila::V1::GetConfigRequest, ::Fila::V1::GetConfigResponse
        rpc :ListConfig, ::Fila::V1::ListConfigRequest, ::Fila::V1::ListConfigResponse
        rpc :GetStats, ::Fila::V1::GetStatsRequest, ::Fila::V1::GetStatsResponse
        rpc :Redrive, ::Fila::V1::RedriveRequest, ::Fila::V1::RedriveResponse
        rpc :ListQueues, ::Fila::V1::ListQueuesRequest, ::Fila::V1::ListQueuesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
