# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: fila/v1/service.proto for package 'fila.v1'

require 'grpc'
require 'fila/v1/service_pb'

module Fila
  module V1
    module FilaService
      # Hot-path RPCs for producers and consumers.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'fila.v1.FilaService'

        rpc :Enqueue, ::Fila::V1::EnqueueRequest, ::Fila::V1::EnqueueResponse
        rpc :StreamEnqueue, stream(::Fila::V1::StreamEnqueueRequest), stream(::Fila::V1::StreamEnqueueResponse)
        rpc :Consume, ::Fila::V1::ConsumeRequest, stream(::Fila::V1::ConsumeResponse)
        rpc :Ack, ::Fila::V1::AckRequest, ::Fila::V1::AckResponse
        rpc :Nack, ::Fila::V1::NackRequest, ::Fila::V1::NackResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
