name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - run: gem build fila-client.gemspec
      - run: ls -la fila-client-*.gem
